version: "3.8"
services:
  web:
    image: web:latest
    build:
      context: .
      dockerfile: backend.Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:8080"
  clery:
    image: celery:latest
    build:
      context: .
      dockerfile: celery.Dockerfile
    depends_on:
      - web
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
